### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by rdohms** [phpextra/sorter#3]
Installation mentions a 1.0 release but there is no release to be found.
Also, consider making install instructions `composer require phpextra/sorter` instead of suggesting editing the json file.

**Comment by jkobus** [comment]
Hello. dev-master is an alias for 1.0.x-dev. Try to change the minimum stability flag and it should work (see https://packagist.org/packages/phpextra/sorter).

**Comment by rdohms** [comment]
@jkobus yes, but then you should suggest at the very least `composer require phpextra/sorter:~1.0@dev`. No need to lower the minimum stability as its not recommended, better to make exceptions for specific packages.
